# Generated by Django 2.0.7 on 2018-07-30 23:59

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_auto_20180728_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repertory',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(-10, 'Inactive'), (0, 'Pending'), (10, 'Cleared')], default=0, help_text='DO NOT CHANGE MANUALLY unless correcting a mistake.  Use the buttons to change state.'),
        ),
    ]
